defaults: &defaults
  adapter: postgresql
  username: postgres
  password: my_postgres_password
  host: localhost

development:
  database: player_images_dev
  <<: *defaults

test: &test
  database: player_images_test
  <<: *defaults

production:
  database: player_images_production
  <<: *defaults
